module.exports = [
  {
    name: "Ирина Рубачева",
    role: "предприниматель",
    vimeo: "340689444",
    hash: "",
    poster: "/assets/img/reviews/video/irina-rubaceva.jpg",
    text: "",
  },
  {
    name: "Вероника Носова",
    role: "Психолог",
    vimeo: "504742082",
    hash: "",
    poster: "/assets/img/reviews/video/veronika-nosova.jpg",
    text: "Меня зовут Вероника, я участвовала во втором потоке курса Ирины Гусинской. Опыт был совершенно необыкновенным. То, что я вначале обозначила, как цель, в течение курса оказалась программой минимум. Я узнала и научилась делать такие вещи, о существовании которых до этого курса я даже не подозревала.",
  },
  {
    name: "Алексей Слободянюк",
    role: "автор, предприниматель, коуч",
    vimeo: "319048278",
    hash: "",
    poster: "/assets/img/reviews/video/aleksej-slobodanuk.jpg",
    text: "",
  },
  {
    name: "Илья Переседов",
    role: "Предприниматель, журналист",
    vimeo: "504742127",
    hash: "f5818c11d0",
    poster: "/assets/img/reviews/video/il-a-peresedov.jpg",
    text: "Прежде, чем говорить о том, почему я выбрал курс Ирины Гусинской, наверное, надо объяснить, вообще, почему я пошёл на писательские курсы, хотя последние 10 лет профессионально занимаюсь созданием текстов для Интернета, для СМИ и называю себя журналистом.",
  },
  {
    name: "Наталья Федорова",
    role: "Директор собственного рекламного агентства, психолог, нейромаркетолог",
    vimeo: "504740639",
    hash: "c93b17cb09",
    poster: "/assets/img/reviews/video/natal-a-fedorova.jpg",
    text: "Хочу поблагодарить Ирину Гусинскую и всю команду курса «Как написать свою книгу за 90 дней». подробно рассказывала об особенностях работы с издательством, синопсисе, самиздате, маркетинге, продвижении книги на рынке, дистрибуции.",
  },
  {
    name: "Андрей Косарев",
    role: "Финансовый администратор",
    vimeo: "504740590",
    hash: "7e76f5e838",
    poster: "/assets/img/reviews/video/andrej-kosarev.jpg",
    text: "Я работаю финансовым администратором в кафе «На полустаночке», живу в городе Екатеринбург и Нижний Тагил, езжу между двумя городами. Мой опыт писательства начался с написания художественной книги под названием «Путешествие разума».",
  },
  {
    name: "Анна Измайлова",
    role: "директор по маркетингу и продажам",
    vimeo: "339687354",
    hash: "",
    poster: "/assets/img/reviews/video/anna-izmajlova.jpg",
    text: "",
  },
  {
    name: "Светлана Богданова",
    role: "писатель, антиквар, специалист по украшениям",
    vimeo: "341270542",
    hash: "",
    poster: null,
    text: "",
  },
  {
    name: "Светлана Критарова",
    role: "доктор-дерматовенеролог, дерматокосметолог",
    vimeo: "339996051",
    hash: "",
    poster: "/assets/img/reviews/video/svetlana-kritarova.jpg",
    text: "",
  },
  {
    name: "Катерина Медведева",
    role: "бизнес-тренер, директор и основатель тренинговой компании",
    vimeo: "317670803",
    hash: "ce4dd890ac",
    poster: "/assets/img/reviews/video/katerina-medvedeva.jpg",
    text: "",
  },
  {
    name: "Лилия Павлова",
    role: "дизайнер, художник",
    vimeo: "339932751",
    hash: "8d0348cfc8",
    poster: "/assets/img/reviews/video/lilia-pavlova.jpg",
    text: "",
  },
  {
    name: "Стелла Малетина",
    role: "психолог, зоопсихолог",
    vimeo: "398458443",
    hash: "",
    poster: "/assets/img/reviews/video/stella-maletina.jpg",
    text: "",
  },
  {
    name: "Наталья Петухова",
    role: "стилист, personal shop assistant, dresser",
    vimeo: "398489275",
    hash: "73a989172e",
    poster: "/assets/img/reviews/video/natal-a-petuhova.jpg",
    text: "",
  },
  {
    name: "Юлия Сорокина",
    role: "арт-критик и куратор современного искусства",
    vimeo: "398530859",
    hash: "",
    poster: "/assets/img/reviews/video/ulia-sorokina.jpg",
    text: "",
  },
  {
    name: "Дарья Корякина",
    role: "практикующий психолог",
    vimeo: "398458837",
    hash: "",
    poster: "/assets/img/reviews/video/dar-a-korakina.jpg",
    text: "",
  },
  {
    name: "Екатерина Казанцева",
    role: "HR-директор",
    vimeo: "398458799",
    hash: "",
    poster: "/assets/img/reviews/video/ekaterina-kazanceva.jpg",
    text: "",
  },
  {
    name: "Елена Орос",
    role: "коуч в сфере семейных отношений",
    vimeo: "403244139",
    hash: "",
    poster: "/assets/img/reviews/video/elena-oros.jpg",
    text: "",
  },
];
